name: Scrape Stooq Profile

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        # 👇👇👇 Dodaj tę sekcję 'env:' 👇👇👇
        env:
          SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
        # 👆👆👆 Koniec dodanej sekcji 👆👆👆
        run: python scraper.py # Ten krok teraz będzie miał dostęp do zmiennej
